[package]
name = "postgres-headers-rs"
version = "0.1.0"
authors = ["Joshua Lockerman <josh@timescale.com>"]
edition = "2018"

build = "build.rs"

[features]
default = []
parse_headers = ["bindgen"]

[dependencies]

[build-dependencies]
bindgen = { version = "0.54", optional = true }
